### ISSUE TITLE
PNG to JPEG Conversion Performance

### ISSUE THREAD

**Issue by bwaldron** [imazen/imageflow-dotnet#26] opened 2021-02-28 19:49 UTC
Imageflow.Net (0.7.21) Imageflow.NativeRuntime.win-x86_64 (1.5.4-rc58)

In converting a normal sized PNG (3000x900) to a JPEG, the job is taking minutes to complete.   This does not happen in any other format or querystring command.  In performance details, can see the primitive_encoder step taking 80+ seconds.

var result = await job.BuildCommandString(new StreamSource(stream, false), new BytesDestination(), "format=jpeg").Finish().InProcessAsync();

![image](https://user-images.githubusercontent.com/981749/109431365-1306f380-79bb-11eb-86f8-243bc1596ec8.png)

**Comment by lilith** [comment] 2021-03-02 02:39
I think this is a duplicate of https://github.com/imazen/imageflow/issues/576

**Comment by lilith** [comment] 2021-03-17 23:30
This was fixed

**Closed by lilith** 2021-03-17 23:30 UTC
